<?php

/*
 *
 * pour ajouter des comptes gmx fraichement achetés
 * 
 * 
 */
require_once (dirname(__FILE__) . '/wp-config.php');
$wp->init();
$wp->parse_request();
$wp->query_posts();
$wp->register_globals();
$wp->send_headers();

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

error_reporting(- 1);
ini_set('display_errors', 'On');
set_error_handler("var_dump");

header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");


$gmx_acts = [
    
    "apiskelofu@gmx.com:bvvpd0wvMw7",
    "deettagoowk@gmx.com:Qt8eq5atlu",
    "fx1ijbays@gmx.com:mzvkznKbzo6",
    "salliekvste@gmx.com:fr7qmVnmqo",
    "jenniefauyj@gmx.com:Wj75be18n",
    "vaniagolay18wh@gmx.com:iuTbm471h8",
    "acroomsud8@gmx.com:wx98diijvF2",
    "kamimayhergr5@gmx.com:m9ymTyhff",
    "ashtonscdzt@gmx.com:Oitl70ded8",
    "danlsarcino@gmx.com:sy4uKrjcw",
    "elenoraphazt@gmx.com:Jytdq9018",
    "moepeazfcp@gmx.com:ii27Dhkmq",
    "bessie707kidane@gmx.com:qt3K81gqq",
    "abbeypalz0xa@gmx.com:ui95gv2dU2v",
    "pampliegoyv@gmx.com:rnr97U7043r",
    "loreenknrodger@gmx.com:qmzywVzp1ra",
    "kylap2deane@gmx.com:mwGz67n9b",
    "tabatha9pzdi@gmx.com:qth69grE82",
    "karon3vsta@gmx.com:gPe0bid5v5h",
    "hollissidzy@gmx.com:shB218h2c",
    "edyth53ldels@gmx.com:sg3tf9wEql",
    "anjelicafilm6@gmx.com:rlFti2vmcpj",
    "bfaulkzva@gmx.com:lx5ldEnsrt",
    "lanell0wvqmarmol@gmx.com:c7mDed7gom",
    "ch1dhirata@gmx.com:lT6w9394w",
    "leoradfjiacor@gmx.com:ifd7vi5Lf",
    "kenithpib046@gmx.com:tmeoiB22s",
    "joolslyerla9nbc@gmx.com:abFs4zbehy",
    "patornese2@gmx.com:jtc7Gholchj",
    "lenitayer56ip@gmx.com:r6nLom2rw",
    "jayneseberti4@gmx.com:zgdXce8yj2",
    "monroe2pnl@gmx.com:Jgn4qaa6c5",
    "kerensa34st@gmx.com:ckiDyu7jvx",
    "hugoudpfwyker@gmx.com:rO7fj0p5o",
    "deidrahu8nbl@gmx.com:p0y77sM6wm",
    "r0arobes@gmx.com:ii55umAzr",
    "loanu4birkey@gmx.com:w1epF169fx",
    "timgironai7em@gmx.com:hX4x26qk56",
    "numuvrgabay@gmx.com:yw61Fjh70d",
    "robyncrocother@gmx.com:i78Jel7x51",
    "marjf2yarosh@gmx.com:Juea28a92",
    "leonordri50@gmx.com:qpga0Mp2y6",
    "aleciazoltydr@gmx.com:Kj3oav3cgs",
    "eradosnxl@gmx.com:wW9myvknv",
    "afxndmangel@gmx.com:dnRqga9932w",
    "pearliek91l@gmx.com:ur25Odicrl",
    "coj1ubbotero@gmx.com:wmc60Uukac",
    "tawannapangtxu@gmx.com:n47gR3cm1k7",
    "gsibrel301@gmx.com:y6j5r03Kfjs",
    "chelseamin13tg@gmx.com:z4r7tUhyd1",
    "dollypp2phelps@gmx.com:Atcoyi1aq4",
    "dionnegumpmp@gmx.com:ecfsOn4oekn",
    "ediephkd@gmx.com:Qczmkbs9qi",
    "kerenzaw4s@gmx.com:b01aQy1n4k",
    "lorne20qnbeckom@gmx.com:n7pd4K81y81",
    "creola4q7lfreije@gmx.com:z1Ivsu4jj",
    "kyleeblzh@gmx.com:fujalwabcR6k",
    "kamsawt@gmx.com:Nq564dt2k",
    "shilagzsak@gmx.com:k7Jkohpk6j",
    "esmeraldaq5beu@gmx.com:gw56c5Sj4fq",
    "harold490rascoe@gmx.com:o3o5i2N8v0",
    "karilkdsp@gmx.com:wmx4Gqkjpj8",
    "dyanman1d@gmx.com:llcW69v2d97",
    "jessica3xwbar@gmx.com:wds1Azfwm9",
    "nnalderwv@gmx.com:qU443lbp69",
    "eppiehc4hora@gmx.com:bE5bll47ck",
    "rosenalevism6v@gmx.com:kjvbs40iG2k",
    "deidrehoyunk@gmx.com:x1w9k92tK0",
    "geordiegxer@gmx.com:l6bloN98p7x",
    "giovannasee8r@gmx.com:uphymxv3rEk",
    "shp8txvliet@gmx.com:x7D7jk4u8pm",
    "sullivanbr3l@gmx.com:Fkaf9xhkuk",
    "dedebatdx@gmx.com:iPe74s0w5ht",
    "anemonekigo@gmx.com:cp8y91p7cVh",
    "arleenf2iunrath@gmx.com:giu1d66Hpys",
    "tenamos7ye@gmx.com:hmGdxi44x",
    "heideo4tfbowin@gmx.com:ctplHj6qzl",
    "robbi1ukztanzer@gmx.com:m3tgq4Dugx1",
    "vernicehildme4@gmx.com:j56qk915Q0",
    "summerpsw@gmx.com:zj0xrivzjZ0",
    "breannebm3br@gmx.com:kM3oezjc6xw",
    "k6g5bzubke@gmx.com:sslrxr64Ryi",
    "benitaqrmmu@gmx.com:z3nioQuyjci",
    "newtoy3trader@gmx.com:vuq825m0Ylg",
    "billi8nstefka@gmx.com:i2u9t56nAv4",
    "paise1gkanipe@gmx.com:Ls46s1605",
    "anselvxim@gmx.com:g23s6fSxbus",
    "gilda3xd@gmx.com:zse07zmX9",
    "rondagpyb5@gmx.com:ga3uBofak0",
    "candace1qaege@gmx.com:osmb48Ay1",
    "myrtavc6@gmx.com:a139yot8Qz",
    "dc8putsler@gmx.com:vjti7Mr5re",
    "korey483mhippen@gmx.com:oslmt77lvQo",
    "alonaggst@gmx.com:Blj9crj025",
    "donettepijlk@gmx.com:t84ddC9p76",
    "lavonda0vubil@gmx.com:tfve1tyVf",
    "nikio24@gmx.com:a1id9M12u77",
    "alison2wisqu@gmx.com:pBffudt0d",
    "francescamzf0na@gmx.com:uh925d0Yx",
    "olivettelipzg@gmx.com:dIfz7duh2",
    "ileneod6cl@gmx.com:xnqo9Ntoo8b",
    "domvqk9g@gmx.com:e052dkFy3",
    "seankyor@gmx.com:wturcC1r63",
    "dionnaben4fn@gmx.com:Vqhm17aow",
    "lorrilentsodv4@gmx.com:qsaCfxqg59",
    "cmishoum3n@gmx.com:yp5npdBtvm",
    "jennywilchx2@gmx.com:l9ajGq2um",
    "deadratarroao@gmx.com:vizjAt2gpl0",
    "tnepavon@gmx.com:vcfvs02eY3",
    "alectimons3hl7@gmx.com:z7jq4fzDr",
    "kristenkmvmar@gmx.com:Uv9kzhj2dj",
    "dey9sawer@gmx.com:rKyhylzhy5",
    "denitatafyt@gmx.com:fuuIm5yerg",
    "gracielaealcf@gmx.com:y8pb4mPs78",
    "ericka8zbiagi@gmx.com:jtZdr5t2y8w",
    "lesleemayden0r@gmx.com:x7xitxjpWn4",
    "brianzbc@gmx.com:e8p559pdeWw",
    "mercye7dnsforza@gmx.com:nqvopaoM5l5",
    "chpzzpwimer@gmx.com:Pquu3ygm4",
    "laurence6omar@gmx.com:hDwz5chsdu",
    "rebecaokotqn@gmx.com:awlh9cW44tf",
    "jasminezzjohem@gmx.com:kg95kbjeA9j",
    "deemerszumnyn93@gmx.com:olzcZ8uok",
    "sammiedupraspv@gmx.com:koUsap5i4d",
    "cassieu4h4gl@gmx.com:tyidPgbm3jh",
    "dysonanhg@gmx.com:hbwh6I4j5t",
    "maryamdaisywum@gmx.com:cb7jvjbyOd",
    "hestermce4ej@gmx.com:wpq9Ilrgu2",
    "jennymeks@gmx.com:hs15Z4vml",
    "robertheardg6e7@gmx.com:tkXz1gn8js",
    "laytonday63xs@gmx.com:hWym0mnv6i",
    "cherlybickes0dm8@gmx.com:clQwx08gq84",
    "brrenzi90n4@gmx.com:fkdquncL93p",
    "cmcallr6tz@gmx.com:bihZbrxqm00",
    "lenorehpmpau@gmx.com:a9lrmapuBtp",
    "marjepovenn@gmx.com:ag69ogiU5",
    "skyv8poeutsey@gmx.com:l382t1hWqy",
    "nataliacu5n@gmx.com:u8nvXblumk",
    "aleishascwsk@gmx.com:seagLon9dfo",
    "bealwpe@gmx.com:nBg4f56pg",
    "chloelop@gmx.com:rnjeW7qjz",
    "irvinyn6apo@gmx.com:b6Yrhjzkz",
    "ariebb6@gmx.com:Fk8msxp53r",
    "lynsay8oclubb@gmx.com:wuGhjd7ad",
    "keelydvry@gmx.com:jph47hneqXs",
    "walterwzbeagle@gmx.com:i7sbepDassl",
    "tophersrockgx@gmx.com:oeWmfb0fgw",
    "ulat9m@gmx.com:nr37Sr2oq7",
    "ansel36july@gmx.com:jn3kLxs76",
    "luciao5@gmx.com:x8eiZ8310q",
    "lethapuhw@gmx.com:isa444knwGl",
    "ivorgbde@gmx.com:zkvfi7Phq",
    "shannaesqe9nm@gmx.com:g07Sz7qze05",
    "russif8tdebona@gmx.com:cg6wdI2r5",
    "cedarpro@gmx.com:t9b3Q4aw2op",
    "asukrudswaby@gmx.com:e8iGe3zfl",
    "lucilefws@gmx.com:nfVx731vn",
    "romal5fhbunce@gmx.com:u9dzz0Yxgm1",
    "cherryrckero@gmx.com:jjik7Wmgery",
    "willodeanfhlev@gmx.com:x9o8Qabi19",
    "nevadah7cjfrett@gmx.com:n0280kymCi",
    "druludvik46db@gmx.com:awbWo58t0f8",
    "shonadnmst@gmx.com:qYrjqy35asf",
    "poppyranck6256@gmx.com:eolcmxwnZ3",
    "zadakry6dxp@gmx.com:vcxnvPip1i",
    "kg7dstrede@gmx.com:i7bubJvb368",
    "taniahalseila@gmx.com:b0ktc9eIv",
    "lissetteuqw@gmx.com:vx6s5tSy37",
    "loqgptofani@gmx.com:fQ7zk5np6",
    "alexis33vmetler@gmx.com:be5F469a2z7",
    "lizzie4dr@gmx.com:Kc3fl59a9o",
    "lezliewon05r@gmx.com:lcls6t7yAa",
    "miriamu3dher@gmx.com:hhfsMu607",
    "lenijx4gosset@gmx.com:x7oj2pWnsl",
    "demelzalaryym@gmx.com:xHrb1sghct0",
    "temekaluskeyob@gmx.com:nsJq93lqd8g",
    "liakas1p@gmx.com:b2Pntspi71",
    "mini5aeost@gmx.com:dC7m77pr0wd",
    "mecrabornml2b@gmx.com:eO8jo7186h",
    "pameliava0y@gmx.com:hb2j3N0e7",
    "chaeungid@gmx.com:a1dp9t05D0a",
    "satchelb4kb@gmx.com:xj4410iKp10",
    "johnsienwmc@gmx.com:p2ld6Jfkkyq",
    "leonardkiez3ko@gmx.com:bvfazH1415y",
    "teganroskamml@gmx.com:slhhlma8J6",
    "vernellfeas2a@gmx.com:Par53c4v0",
    "eddyzenzenow2@gmx.com:jp4hP2s0gm",
    "breana5kjxshakin@gmx.com:ffUz0vgvudi",
    "robbietarn@gmx.com:r09bF6x3e1p",
    "edricils@gmx.com:m4eJi5l7cxv",
    "fortune15tqp@gmx.com:zgsja2kiZ0",
    "carlmjc@gmx.com:zbbbuv9hIvs",
    "elnorae8summa@gmx.com:wuEq3142y",
    "langdonc0s@gmx.com:o58mU5rq57",
    "isiahfdnnorsen@gmx.com:ps8s660O5a",
    "sandyma6c5@gmx.com:r2mq31Sk9",
    "robinj4earvin@gmx.com:s4845znEg",
    "odeliaschjk@gmx.com:qd3ePw0m2",
    "oletav7ot@gmx.com:qi5Mhy2ya",
    "bryonyclrfocke@gmx.com:s57qlIo6lcu"
    
    
];

$gmxActMg = new \spamtonprof\stp_api\GmxActManager();

foreach ($gmx_acts as $gmx_act) {
    $gmx_act = explode(":", $gmx_act);
    $gmxActMg->add(new \spamtonprof\stp_api\GmxAct(array(
        'mail' => $gmx_act[0],
        'password' => $gmx_act[1]
    )));
}